# Generated by Django 5.0.4 on 2024-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury_date',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='recovery_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
