# Generated by Django 5.1.7 on 2025-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_player_injury_date_alter_player_recovery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('match_income', models.PositiveIntegerField(default=0)),
                ('sponsors_income', models.PositiveIntegerField(default=0)),
                ('transfers_income', models.PositiveIntegerField(default=0)),
                ('prize_income', models.PositiveIntegerField(default=0)),
                ('merch_income', models.PositiveIntegerField(default=0)),
                ('other_income', models.PositiveIntegerField(default=0)),
                ('transfers_expense', models.PositiveIntegerField(default=0)),
                ('salary_expense', models.PositiveIntegerField(default=0)),
                ('academy_expense', models.PositiveIntegerField(default=0)),
                ('infra_expense', models.PositiveIntegerField(default=0)),
                ('merch_expense', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
