# Generated by Django 5.1.7 on 2025-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_player_injury_date_player_recovery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='expiration_date',
            field=models.DateField(default='2031-01-01'),
        ),
        migrations.AlterField(
            model_name='player',
            name='injury_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='recovery_date',
            field=models.DateField(),
        ),
    ]
