# Generated by Django 5.1.7 on 2025-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_player_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcine',
            name='injury_date',
            field=models.DateField(default='2031-01-01'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='recovery_date',
            field=models.DateField(default='2031-01-01'),
        ),
    ]
