# Generated by Django 5.1.7 on 2025-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100, verbose_name='Команда 1')),
                ('team2', models.CharField(max_length=100, verbose_name='Команда 2')),
                ('match_date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
            ],
        ),
    ]
