# Generated by Django 5.1.7 on 2025-04-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сектора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sectors/', verbose_name='Изображение сектора')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('total_seats', models.PositiveIntegerField(default=100, verbose_name='Всего мест')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='shop.match')),
            ],
        ),
    ]
