# Generated by Django 5.1.7 on 2025-04-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_sector_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='shop.order'),
        ),
    ]
