# Generated by Django 5.1.7 on 2025-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_match_ticket_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sector',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='row_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Ряд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='rows',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество рядов'),
        ),
        migrations.AddField(
            model_name='sector',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10, verbose_name='Мест в ряду'),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='seat_number',
            field=models.PositiveIntegerField(verbose_name='Место в ряду'),
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together={('sector', 'row_number', 'seat_number')},
        ),
    ]
